image: Visual Studio 2019
version: '{build}'
clone_depth: 10
environment:
    CLI_VERSION: 3.1.300
init:
  - git config --global core.autocrlf input
build_script:
  - ps: .\fake.cmd --target pack
test: off
artifacts:
  - path: bin\*.nupkg
